apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-db
  labels:
    app: auth-db
    tier: database

spec:
  selector:
    matchLabels:
      app: auth-db

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: auth-db
        tier: database

    spec:
      containers:
        - name: auth-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: postgres_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /data/auth
              name: auth-db-volume

      restartPolicy: Always
      volumes:
        - name: auth-db-volume
          persistentVolumeClaim:
            claimName: auth-db-volume
---
apiVersion: v1
kind: Service

metadata:
  name: auth-db
  labels:
    app: auth-db
    tier: database

spec:
  ports:
    - port: 5432
      targetPort: 5432

  selector:
    app: auth-db
    tier: database