apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-db
  labels:
    app: auth-db
    tier: database

spec:
  selector:
    matchLabels:
      app: auth-db

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: auth-db
        tier: database

    spec:
      containers:
        - name: auth-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: dienwagen_auth
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service

metadata:
  name: auth-db
  labels:
    app: auth-db
    tier: database

spec:
  ports:
    - port: 5432
      targetPort: 5432

  selector:
    app: auth-db
    tier: database