apiVersion: v1
kind: PersistentVolume

metadata:
  name: auth-db-volume
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /data/auth

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: auth-db-volume-claim

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi