apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: auth-db-volume
  labels:
    app: auth-db-volume

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi