apiVersion: apps/v1
kind: Deployment

metadata:
  name: customers-db
  labels:
    app: customers-db
    tier: database

spec:
  selector:
    matchLabels:
      app: customers-db

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: customers-db
        tier: database

    spec:
      containers:
        - name: customers-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: dienwagen_requests
          ports:
            - containerPort: 5431
---
apiVersion: v1
kind: Service

metadata:
  name: customers-db
  labels:
    app: customers-db
    tier: database

  spec:
    ports:
      - port: 5431
        targetPort: 5431

    selector:
      app: customers-db
      tier: database