apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests-db
  labels:
    app: requests-db
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requests-db

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: requests-db
        tier: database

    spec:
      containers:
        - name: requests-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: dienwagen_requests
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: requests-db
  labels:
    app: requests-db
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  
  selector:
    app: requests-db
    tier: database