apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests-deployment
  labels:
    app: requests-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requests-service
  strategy: {}
  template:
    metadata:
      labels:
        app: requests-service
    spec:
      containers:
        - name: requests-service
          image: rajkarkhanis/dienwagen-requests
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: requests-service
spec:
  selector:
    app: requests-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
