apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests-service
  labels:
    app: requests-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requests-service
  strategy: {}
  template:
    metadata:
      labels:
        app: requests-service
    spec:
      containers:
        - name: requests-service
          image: rajkarkhanis/dienwagen-requests
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://requests-db:5432/dienwagen_requests
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
---
apiVersion: v1
kind: Service
metadata:
  name: requests-service
spec:
  selector:
    app: requests-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30777
  type: NodePort
